# Generated by Django 6.0.5 on 2026-05-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(choices=[(1, 'Gold'), (2, 'Diamond'), (3, 'Silver'), (4, 'Platinum'), (5, 'Pearl'), (6, 'Gemstone')], unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(choices=[(1, '22K'), (2, '21K'), (3, '18K'), (4, 'Traditional'), (5, 'Natural Diamond'), (6, 'Lab Grown Diamond'), (7, 'Polki Diamond'), (8, 'American Diamond'), (9, 'Bridal Diamond'), (10, '950 Platinum'), (11, '900 Platinum'), (12, 'Platinum Bridal'), (13, 'Couple Band Platinum'), (14, 'Freshwater Pearl'), (15, 'Natural Pearl'), (16, 'Cultured Pearl'), (17, 'South Sea Pearl'), (18, 'Ruby'), (19, 'Emerald'), (20, 'Sapphire'), (21, 'Topaz'), (22, 'Opal'), (23, 'Amethyst')])),
                ('is_visible', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('menue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pages.menue')),
            ],
            options={
                'ordering': ['order', '-id'],
                'unique_together': {('menue', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='products/')),
                ('manual_price_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_auto_update_price', models.BooleanField(default=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in gram', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('short_description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('making_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.category')),
                ('menue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.menue')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pages.subcategory')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
