# Generated by Django 6.0.5 on 2026-05-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_videogallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
