# Generated by Django 6.0.5 on 2026-05-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_photogallery_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogallery',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='videogallery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='youtube_id',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='youtube_url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
